//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityFramework.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int Id { get; set; }
        public string name { get; set; }
        public decimal unitprice { get; set; }
        public int stockAmount { get; set; }
    }
}
